version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - '3000:4000'
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=mypassword
    env_file:
      - ./.env.local
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
