version: '3'
services:
  node-app:
    build: .
    volumes:
      - ./:/app:ro
      - /app/node_modules

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
