version: '3'
services:
  nginx:
    ports:
      - '80:80'
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    env_file:
      - ./.env.prod
    command: npm start

  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
