version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - '3000:4000'
    volumes:
      - ./:/app:ro
      - /app/node_modules
    # environment:
    #   - MONGO_USER=root
    #   - MONGO_PASSWORD=mypassword
    #   - SESSION_SECRET=secret
    env_file:
      - ./.env.local
    command: npm run dev

  # mongo:
  # ports:
  # - '27017:27017'
