version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - '3000:4000'
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env.local
    command: npm run dev
